- hosts: local
  user: cloud
  sudo: yes

  tasks:
    - name: gocd repository is present
      apt_repository:
        repo="deb http://dl.bintray.com/gocd/gocd-deb /"
        state=present

    - name: gocd repository key is present
      apt_key:
        url="https://bintray.com/user/downloadSubjectPublicKey?username=gocd"
        state=present
        
    - name: go server and agent
      apt:
        update_cache=yes
        pkg="{{ item }}"
        state=present
      with_items:
        - go-server
        - go-agent
