- hosts: local
  user: cloud
  sudo: yes

  tasks:
    - name: Jenkins key server is known
      apt_key:
        url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key
        state=present

    - name: Jenkins apt server is known
      apt_repository:
        repo="deb http://pkg.jenkins-ci.org/debian binary/"
        state=present

    - name: apt cache is up-to-date
      apt:
        update_cache=yes
        cache_valid_time=0

    - name: system is up-to-date
      apt:
        upgrade=full

    - name: packages installed
      apt:
        pkg="{{ item }}"
        state=present
      with_items:
        - libguestfs-tools
        - jenkins

    - name: pip packages installed
      apt:
        name="{{ item }}"
      with_items:
        - python-glanceclient
        - python-novaclient
        - python-neutronclient
        - python-heatclient
        - python-openstackclient
        - python-cinderclient
        
    - name: jenkins is up
      service:
        name=jenkins
        state=started
        enabled=yes