- hosts: local
  user: cloud
  sudo: yes

  tasks:
    - name: apt cache is up-to-date
      apt:
        update_cache=yes
        cache_valid_time=3600

    - name: system is up-to-date
      apt:
        upgrade=full
        
    - name: packages installed
      apt:
        pkg="{{ item }}"
        state=present
      with_items:
        - libguestfs-tools